<?php

   
    /**********************************************************************************
      CONTROLLARE IL TOKEN: STARE ATTENTI ALL'IP
    *************************************************************************************/
    //casa Vale
    //$token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6Ijk2NDI4MzkyLTc4YTEtNDMzMS05NTU0LTc5ZmYwNTBkYzhiYiIsImlhdCI6MTY4NDY4ODY5MSwic3ViIjoiZGV2ZWxvcGVyLzkwNWExNWI2LWQ2MmItZTA4MC00MTk5LWZlMDBiZmQ4N2ZmYyIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyI0Ny41My43Ni4xMjUiXSwidHlwZSI6ImNsaWVudCJ9XX0.lQf068k7LAgIUCBxx8zqM2AeDIep9CNpUUnUT3YUTFfpFgx8bt5OyDkUQD0ZMk4XVay5njN-FGIJLDdyaOkjFQ";
    
    //casa mia
    //$token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjIyM2NjMzZkLTIxZTgtNDNiYy1iYjY0LTFlYzIwMTJmYjVhMyIsImlhdCI6MTY4NDI0NTgxMywic3ViIjoiZGV2ZWxvcGVyLzkwNWExNWI2LWQ2MmItZTA4MC00MTk5LWZlMDBiZmQ4N2ZmYyIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyIyLjM4LjE1MC4yMDIiXSwidHlwZSI6ImNsaWVudCJ9XX0.SvRZxB-v3KKuQBhvdftmorCJ0mSd01GQoN9GG-wpMbhwZM3W-4Asm7iwxdSDY2SoVjhmne1edrt1T5PeiKzfdw";
    
    //uni
    $token ="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImE2MmU1MzJiLWM1YzYtNDRmYS1hOWM2LWMxMmYxN2U3ZDU2MSIsImlhdCI6MTY4NDc0NzA3Mywic3ViIjoiZGV2ZWxvcGVyLzkwNWExNWI2LWQ2MmItZTA4MC00MTk5LWZlMDBiZmQ4N2ZmYyIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyIxNTEuOTcuMTU3LjE4MCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.e2NOZAg9Cvo-dtYYceAIbC9zn8XzWD28UVENCdLcvTTOTtkKUR5lQXLDW7OVR_I_Kg5qtrdkSSZuvcUvCFEvbw";




?>