<?php

   
    /**********************************************************************************
      CONTROLLARE IL TOKEN: STARE ATTENTI ALL'IP
    *************************************************************************************/
    //casa Vale
    //$token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjhhNTEyNTU1LWUwODEtNDM1OS05MTY1LTY3OTMxZWQyYWM0OCIsImlhdCI6MTY4NDkzNzkzMCwic3ViIjoiZGV2ZWxvcGVyLzkwNWExNWI2LWQ2MmItZTA4MC00MTk5LWZlMDBiZmQ4N2ZmYyIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyI5My4xNDQuNTAuMTE2Il0sInR5cGUiOiJjbGllbnQifV19.Ev6qKFz6LIr2tob_AWMmLsMg5bWozX6ZmLq79Jcqq8JGern-nRaOqMRKbv_mSDlKvPTiDYizyOAhQ1kgFyzndw";
    
    //casa mia
    $token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjkyOWFjNDg4LWQ3MTctNDI3MS1hODFhLTQzNTVmMjJmMTgyNiIsImlhdCI6MTY4NDk1NDM5MCwic3ViIjoiZGV2ZWxvcGVyLzkwNWExNWI2LWQ2MmItZTA4MC00MTk5LWZlMDBiZmQ4N2ZmYyIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyIyLjM4LjE1MC42MyJdLCJ0eXBlIjoiY2xpZW50In1dfQ.87cdx0xO6mndJOAPiJdDYco40ziipTj-g33NG4Lav9q67L0I55EBdB0pHCvVht5Qr3NMOfy_aawiG-Zr5f-RRQ";
    
    //uni
    //$token ="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImE2MmU1MzJiLWM1YzYtNDRmYS1hOWM2LWMxMmYxN2U3ZDU2MSIsImlhdCI6MTY4NDc0NzA3Mywic3ViIjoiZGV2ZWxvcGVyLzkwNWExNWI2LWQ2MmItZTA4MC00MTk5LWZlMDBiZmQ4N2ZmYyIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyIxNTEuOTcuMTU3LjE4MCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.e2NOZAg9Cvo-dtYYceAIbC9zn8XzWD28UVENCdLcvTTOTtkKUR5lQXLDW7OVR_I_Kg5qtrdkSSZuvcUvCFEvbw";




?>