<?php

   
    /**********************************************************************************
      CONTROLLARE IL TOKEN: STARE ATTENTI ALL'IP
    *************************************************************************************/
    //casa Vale
    //$token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjJmM2U2ZGM1LTM5YjktNDMxYy05MGY4LTNlMzFmZjMxNGFmYiIsImlhdCI6MTY4NTE5ODAyNiwic3ViIjoiZGV2ZWxvcGVyLzkwNWExNWI2LWQ2MmItZTA4MC00MTk5LWZlMDBiZmQ4N2ZmYyIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyI5My4xNDQuNTkuMjM5Il0sInR5cGUiOiJjbGllbnQifV19.HASPMGC-eiOTD0o5UtWgGN9NCItxjE0t0_36E5a7hifRr1VXXGKtQPTZBV0aN6g9aE47ZI5ni7dAOUaFAF9kVw";
    
    //casa mia
    $token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImMyYzBiY2Q4LThmYzMtNGFlOS1iOGE2LTFkYWJlZmVjM2FiYiIsImlhdCI6MTY4NTI4MDk5NCwic3ViIjoiZGV2ZWxvcGVyLzkwNWExNWI2LWQ2MmItZTA4MC00MTk5LWZlMDBiZmQ4N2ZmYyIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyIyLjQ0LjEzOC4xMzYiXSwidHlwZSI6ImNsaWVudCJ9XX0.IwMnhnXV2HHZRt7amjFsELrwDekf_r8Od4h-k1rVbnujLHrpeyyjdmkCrp-CoPqsQUjRWZB2YNugfDrFnJJ_Mw";
    
    //uni
    //$token ="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImZhMzExNGE4LWM3MDMtNDY1MS1hOGI0LTc4YTAzYzE4NjM1ZSIsImlhdCI6MTY4NTAxMDkzMywic3ViIjoiZGV2ZWxvcGVyLzkwNWExNWI2LWQ2MmItZTA4MC00MTk5LWZlMDBiZmQ4N2ZmYyIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyIxNTEuOTcuMTQ3Ljk4Il0sInR5cGUiOiJjbGllbnQifV19.jO4qurMQObTYtaszyt2Wq5qo6x4AlGUwu9--HNwAlcdwFfBB5nn7TCZFWH33TCdVLVCZPzl7y7LK29A0Z2YVpw";




?>